
package Interfaz;

import Clases.Archivos;
import Clases.Global;
import Clases.Estructuras.ListaUsuario;
import Clases.Estructuras.Estructuras;
import Clases.Nodos.Nodo_Usuario;

/**
 * @author MorseIván
 */
public class Creacion_Usuarios extends javax.swing.JFrame {
     Archivos ar = new Archivos();
       
        
    
    public Creacion_Usuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    private Estructuras _lp;
    private Estructuras _lz;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugadorPlantas = new javax.swing.JButton();
        btnJugadorZombies = new javax.swing.JButton();
        btnEliminarDatosUsuarios = new javax.swing.JButton();
        btnInsertarPlanta = new javax.swing.JButton();
        btnInsertarZombies = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLANTS VS ZOMBIES GUATEMALTECO 1.0");
        setFont(new java.awt.Font("Adobe Arabic", 1, 12)); // NOI18N
        setIconImage(getIconImage());

        btnJugadorPlantas.setText("Jugador Plantas");
        btnJugadorPlantas.setMaximumSize(new java.awt.Dimension(113, 23));
        btnJugadorPlantas.setMinimumSize(new java.awt.Dimension(113, 23));
        btnJugadorPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorPlantasActionPerformed(evt);
            }
        });

        btnJugadorZombies.setText("Jugador Zombies");
        btnJugadorZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorZombiesActionPerformed(evt);
            }
        });

        btnEliminarDatosUsuarios.setText("Eliminar Datos");
        btnEliminarDatosUsuarios.setMaximumSize(new java.awt.Dimension(113, 23));
        btnEliminarDatosUsuarios.setMinimumSize(new java.awt.Dimension(113, 23));
        btnEliminarDatosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDatosUsuariosActionPerformed(evt);
            }
        });

        btnInsertarPlanta.setText("Insertar Plantas");
        btnInsertarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPlantaActionPerformed(evt);
            }
        });

        btnInsertarZombies.setText("Insertar Zombies");
        btnInsertarZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarZombiesActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Presentaciones/Presentacion.png"))); // NOI18N

        jButton5.setText("Comenzar Juego");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminarDatosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInsertarZombies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJugadorZombies, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btnJugadorPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnJugadorPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJugadorZombies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertarZombies)
                        .addGap(10, 10, 10)
                        .addComponent(btnInsertarPlanta))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarDatosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugadorPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorPlantasActionPerformed
        Usuario_Plantas UP = new Usuario_Plantas();
        UP.setVisible(true);
       
    }//GEN-LAST:event_btnJugadorPlantasActionPerformed

    private void btnJugadorZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorZombiesActionPerformed
        Usuario_Zombies UZ = new Usuario_Zombies();
        UZ.setVisible(true);
    }//GEN-LAST:event_btnJugadorZombiesActionPerformed

    private void btnEliminarDatosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDatosUsuariosActionPerformed
        ListaUsuario l = Global.getInstance().usuario;
        Estructuras p = Global.getInstance().plantas;
        Estructuras z = Global.getInstance().zombies;
        l.vaciarLista();
        p.vaciarEstructura();
        z.vaciarEstructura();
        
    }//GEN-LAST:event_btnEliminarDatosUsuariosActionPerformed

    
    private void btnInsertarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPlantaActionPerformed
         ListaUsuario lusr = Global.getInstance().usuario;
        Nodo_Usuario nusr = lusr.ninicio;
        while ( nusr != null)
        {
            if (nusr.tipo == 1 )
            {
                _lp = nusr.objplantas;
                break;
            }
            nusr = nusr.sig;
        }
        if ( _lp != null )
        {
                CatalogoPlantas cp = new CatalogoPlantas();
        cp.lplantas = _lp;
        cp.setVisible(true); 
        }
    }//GEN-LAST:event_btnInsertarPlantaActionPerformed

    private void btnInsertarZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarZombiesActionPerformed
         ListaUsuario lusr = Global.getInstance().usuario;
        Nodo_Usuario nusr = lusr.ninicio;
        while ( nusr != null)
        {
            if (nusr.tipo == 2 )
            {
                _lz = nusr.objzombies;
                break;
            }
            nusr = nusr.sig;
        }
        if ( _lz != null)
        {
              CatalogoZombies cz = new CatalogoZombies();
              cz.lzombies = _lz;
              cz.setVisible(true);
        }
      
    }//GEN-LAST:event_btnInsertarZombiesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Dimensiones_Tablero dt = new Dimensiones_Tablero();
dt.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarDatosUsuarios;
    private javax.swing.JButton btnInsertarPlanta;
    private javax.swing.JButton btnInsertarZombies;
    private javax.swing.JButton btnJugadorPlantas;
    private javax.swing.JButton btnJugadorZombies;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


}